### ISSUE TITLE
How do you learn to write such huge programs?

### ISSUE THREAD

**Issue by satyaSK** [hnarayanan/artistic-style-transfer#5]
Hi,
I recently read your blogpost on style transferring. I understood every single bit of it, but I was wondering how you may have written it(the code)? As a beginner, whenever I take up a project, I find myself able to understand complete concepts, but still look for pieces of code online(for syntax and sometimes concepts too). And later on I start feeling that I didn't do things by myself. So what is the way to learn and implement a project? After looking at your code, it was easy to understand everything, but the fact that you wrote it from start to end ,by yourself, makes me feel intimidated. I seriously want to know the approach you and many other developers take when it comes to learning and implementing.

**Comment by hnarayanan** [comment]
It mostly just comes from experience. And it may sound obvious but:

You take any project you're trying to do and break it down into its many sub parts. Try to work on each one systematically (learning whatever you need along the way) to get the whole thing working. There is no real magic to it, just spending a lot of time and progressing methodically.
