### ISSUE TITLE
Problem running TF on Python 2.7

### ISSUE THREAD

**Issue by gofornaman** [hnarayanan/artistic-style-transfer#6]
Hey, I came across your work on style transfer and found it amazing. But I'm getting stuck on the implementation part. Your code is for Python 2.7 but Tensorflow supports 3.5 and above right?

**Comment by hnarayanan** [comment]
This code has only been written and tested on Python 2.7. You’re free to contribute improvements to make it work on Python 3. 😀

**Comment by gofornaman** [comment]
How do I make tensorflow compatible since tensorflow doesn't work with python 2.7.

**Comment by hnarayanan** [comment]
TensorFlow supports both 2.7 and recent Python 3.x.
