### ISSUE TITLE
what has to be done here?

### ISSUE THREAD

**Issue by kunaldhariwal** [hnarayanan/artistic-style-transfer#7]
Could not find a version that satisfies the requirement tensorflow==1.4.0 (from -r requirements.txt (line 60)) (from versions: )
No matching distribution found for tensorflow==1.4.0 (from -r requirements.txt (line 60))

**Comment by hnarayanan** [comment]
How is your python/pip environment setup?

1.4.0 is a recent and supposedly well-supported version of TensorFlow, so what you're seeing shouldn't happen. I see it listed as a legit pip package: https://pypi.python.org/pypi/tensorflow/1.4.0

**Comment by kunaldhariwal** [comment]
Solved. I used anaconda to solve this issue but i still have troubles to use the project.
i mean, how do i get the output or insert any new image to see the modified output?
how would it work in jupyter notebook?

**Comment by hnarayanan** [comment]
Please actually open the notebook and try it. You'll see that one of the first lines is literally opening a file in a folder path using Pillow. I am going to close this thread now as this is not a support forum, it is a way to point out issues and hopefully offer solutions.

Good luck!

**Comment by kunaldhariwal** [comment]
Thanks
