### ISSUE TITLE
not sure how to fix this error

### ISSUE THREAD

**Issue by skykorbgoodman** [hnarayanan/artistic-style-transfer#8]
I'm new to code, in general, I was wondering if there is an easy fix to this I'm not able to find

Collecting tensorflow==1.4.0 (from -r requirements.txt (line 60))
  Could not find a version that satisfies the requirement tensorflow==1.4.0 (from -r requirements.txt (line 60)) (from versions: )
No matching distribution found for tensorflow==1.4.0 (from -r requirements.txt (line 60))

Thank you very much,
Sky Goodman

**Comment by hnarayanan** [comment]
I am sorry, I do not have time to help you with this. It is likely that an updated version has replaced it.
