### ISSUE TITLE
Reuse

### ISSUE THREAD

**Issue by SalAlba** [hnarayanan/artistic-style-transfer#9]
Good project and explanation, I have one question when we train our model on specific style, can we reuse it with another images ? with less time of moving style  ?

Do I have make this long process every time whenever I want  one style to another image ?

**Comment by hnarayanan** [comment]
This is a good question. For the method used in this repository, you need to go through the long process each time.

If you instead use a better algorithm, you need to only train once per style. Then the actual act of applying the style to any given input image is super fast. Please see e.g. https://github.com/lengstrom/fast-style-transfer.
